
source "https://rubygems.org"

group :prodiuction do
	gem 'sinatra'
	gem 'json'
end


group :development do
  # gem 'guard'
  # gem 'guard-minitest'
  # gem 'mocha'	
  # gem 'minitest-reporters'
  # gem 'rake'
  gem 'rerun'
end